server:
  port: 85
  servlet:
    context-path: /newbeemall

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: dev

local:
  uploadDir: D:\\upload

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
